name: Get Lives

on:
  schedule:
    - cron: '5 */8 * * *'
  workflow_dispatch:

jobs:
  get_streams:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pytz

    - name: Set up environment variables
      run: |
        echo "URL_1=${{ secrets.URL_1 }}" >> $GITHUB_ENV
        echo "URL_2=${{ secrets.URL_2 }}" >> $GITHUB_ENV
        echo "URL_3=${{ secrets.URL_3 }}" >> $GITHUB_ENV
        echo "JK=${{ secrets.JK }}" >> $GITHUB_ENV

    - name: Run Python script
      run: python ./getm.py

    - name: Commit å’Œ push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add zo.txt zoo.txt
        git commit -m "Update" --allow-empty
        git push
